# Generated by Django 4.2.6 on 2024-04-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
