# Generated by Django 4.2.6 on 2024-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
